[project]
name = "task-4"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "aiogram>=3.23.0",
    "environs>=14.5.0",
    "pandas>=2.3.3",
]
